server:
  port: 5557
spring:
  application:
    name: rocketmq-exporter
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  config: classpath:logback.xml

rocketmq:
  config:
    webTelemetryPath: /metrics
    rocketmqVersion: 4_2_0
    namesrvAddr: 127.0.0.1:9876 #
    enableCollect: true

task:
  count: 5
  collectTopicOffset:
    cron: 15 0/1 * * * ?
  collectConsumerOffset:
    cron: 15 0/1 * * * ?
  collectBrokerStatsTopic:
    cron: 15 0/1 * * * ?
  collectBrokerStats:
    cron: 15 0/1 * * * ?
  collectBrokerRuntimeStats:
    cron: 15 0/1 * * * ?
